import { initializeApp } from 'firebase/app';
import { getAuth } from 'firebase/auth';
import { getFirestore } from 'firebase/firestore';
import { getStorage } from 'firebase/storage';
const cfg={apiKey:import.meta.env.VITE_FIREBASE_API_KEY,authDomain:import.meta.env.VITE_FIREBASE_AUTH_DOMAIN,projectId:import.meta.env.VITE_FIREBASE_PROJECT_ID,storageBucket:import.meta.env.VITE_FIREBASE_STORAGE_BUCKET,messagingSenderId:import.meta.env.VITE_FIREBASE_MESSAGING_SENDER_ID,appId:import.meta.env.VITE_FIREBASE_APP_ID};
const placeholderValues=['your_api_key','your_project.firebaseapp.com','your_project_id','your_project.appspot.com','your_sender_id','your_app_id'];
export const firebaseReady=Object.values(cfg).every(value=>value&& !placeholderValues.includes(value));
const app=firebaseReady?initializeApp(cfg):null;
export const auth=app?getAuth(app):null;
export const db=app?getFirestore(app):null;
export const storage=app?getStorage(app):null;
